### ISSUE TITLE
Testing sos-sas module

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-sas#1]
As title.

**Comment by BoPeng** [comment]
Yes, it would be very helpful for you to try to setup SAS/Jupyter/SoS through sos-sas, share your experience as installation instruction, and report problems here.

**Comment by BoPeng** [comment]
Linux was listed as a dependency for sas-kernel last year but they have removed it (see log message for their readme). I assume that this means sas-kernel should work under windows.

Setting up SAS with Jupyter/SoS and R would also be helpful to you in case you would like to mix and match SAS and R code in your analysis.

**Comment by HenryLeongStat** [comment]
Will do! 

Actually, people here only use `R` and `sas`. I heard some complaints about the inconvenience for communication (few of them know both). I think it is a good opportunity to introduce them `SoS` and will try to bring that up later when I have a chance!

**Comment by BoPeng** [comment]
Make sure sos works well for this case first, especially because I do not use windows so SoS is not well tested under windows. :-) I suppose you can be our windows tester if you are the only frequent windows user.

**Comment by HenryLeongStat** [comment]
OK, I will make sure it working on `windows 7` first. It does surprise me that everyone is still using `windows 7` here... Will follow the instruction for windows installation of `SoS`! :D

**Comment by BoPeng** [comment]
If I have to use windows and have a choice between windows 7 and 10, I would definitely choose 7.

**Comment by HenryLeongStat** [comment]
But why? When I tried to boot the other desktop and install `Ubuntu` there, I find that there is a `Ubuntu terminal` for Windows 10. Most of the softwares and supports are based on Windows 10 instead of Windows 7, aren't they?

**Comment by HenryLeongStat** [comment]
I also have a question for the `sas kernel`. When the dataset is very large, sometimes it would be lagged to import the dataset using `sas GUI`. Would that be less lagging to use `sas kernel` in `Jupyter Notebook` to import the large dataset?

**Comment by BoPeng** [comment]
The UI if windows ten really sucks, because it tries to accommodate both traditional UI and touch screen. The start menu is less intuitive and it even have two setting systems, control panel for traditional use and settings for touch screen, and some settings are in one system not in another. I also had lot of trouble with windows 10 on my surface book, which was supposed to be the top machine for windows 10.

But nothing compared to the auto update stuff. I have many instanances that when I need to use my surface book, it starts with a “updating” screen and update itself for 30 minutes...

**Comment by BoPeng** [comment]
No. Jupyter/sas-kernel would not improve performance.

**Comment by HenryLeongStat** [comment]
>The UI of windows ten really sucks, because it tries to accommodate both traditional UI and touch screen....

I see... Didn't have much experience with windows 10 though, the only desktop with windows 10 is taken by my elder brother at home. And not rich enough to buy a surface book. :sweat_smile:

>No. Jupyter/sas-kernel would not improve performance.

OK, so the only way to improve the performance should be using `SAS` CLI I guess? I will try that later. Start to understand why CLI is better than GUI in a lot of cases, not only the cases caring about performance, but also the ability to be reproducible.

**Comment by BoPeng** [comment]
What I meant was that if the dataset is large, most of the resources would be spent on data importing/analysis so GUI, Notebook or CLI would not make a big difference. Differences would only be noticeable when you have limited hardware resource (so that GUI can be a burden by itself) and/or you are analyzing small/medium sized data (for which interface lag is noticeable).

**Comment by HenryLeongStat** [comment]
I see! What bugs me is that there is a VM for protecting the data, and it is extremely lagged to do anything there, even open a SAS GUI. However, all the work has to be done there due to all the data storing there. The hardware is powerful, but shared by 25 VMs. 

Anyway, I think that is a very good idea to use `SoS` for the works, since all the works are required to be reproducible. `SoS` is a great way to show the report especially for users with different language-preferences (hard to read the codes even if they are well-commented).

**Comment by BoPeng** [comment]
Should work under windows now.
